version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: ${DB_HOST}
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./data/mongo:/data/db
  scraper:
    build: .
    container_name: cyber_scraper
    restart: always
    ports:
      - ${APP_PORT}:3000
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
    volumes:
      - .:/app
      - /app/node_modules

